import { loadCatalog, type ModelCatalog } from "@seri/model-catalog";
import { printWarning } from "../cli/output";
import bundledManifest from "./catalog-manifest.json";

// The CLI's own copy of @seri/model-catalog's fallback manifest (generated by
// packages/model-catalog/src/generate.ts, committed here rather than fetched at runtime). A
// plain .json import, unlike rg-vendored.bin's raw binary asset (vendorRipgrep.ts): bun's
// bundler already treats a JSON import as a module and inlines it at build time, so it needs no
// `with { type: "file" }` to survive inside the compiled binary.
const FALLBACK_MANIFEST = bundledManifest as ModelCatalog;

// The one dispatch point apps/cli calls to get the model catalog: @seri/model-catalog does the
// fetch-with-fallback and the in-memory caching, this just supplies the CLI's own bundled
// fallback and warns once when that fallback is what actually got used.
export async function getModelCatalog(fetchFn: typeof fetch = fetch): Promise<ModelCatalog> {
  const catalog = await loadCatalog(FALLBACK_MANIFEST, fetchFn);
  if (catalog === FALLBACK_MANIFEST) {
    printWarning("could not reach models.dev; using the bundled model catalog");
  }
  return catalog;
}
